import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
let server,base;
const root=fileURLToPath(new URL('../../site/',import.meta.url));
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.py':'text/plain','.pdf':'application/pdf'};
test.beforeAll(async()=>{
  // Temporary loopback-only test fixture, not a hosting/deployment adapter.
  server=createServer(async(req,res)=>{
    const file=new URL(req.url,'http://localhost').pathname;
    if(file!=='/' && !/^\/[a-z-]+\.(html|js|css|svg|py|pdf)$/.test(file)){res.writeHead(404).end();return;}
    try{const name=file==='/'?'index.html':file.slice(1);const data=await readFile(path.join(root,name));
      res.writeHead(200,{'Content-Type':types[path.extname(name)]});res.end(data);
    }catch{res.writeHead(404).end();}
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  base=`http://127.0.0.1:${server.address().port}`;
});
test.afterAll(async()=>{await new Promise(resolve=>server.close(resolve));});
test('compact results, compressed views and projection explanation stay local',async({page})=>{
  const errors=[],external=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{if(!request.url().startsWith(base))external.push(request.url());});
  await page.goto(base);
  await expect(page.locator('#coordinates')).toContainText('P4096');
  await expect(page.locator('#dimension')).toHaveValue('3');
  await expect(page.locator('#view-label')).toContainText('3D · illustrative');
  await expect(page.locator('.results-table thead th')).toHaveCount(4);
  await expect(page.locator('.results-table tbody tr')).toHaveCount(1);
  await expect(page.locator('.results-table')).not.toContainText('Directions used');
  await expect(page.locator('.results-table tbody td')).toHaveText(['<7','<4','<4','<3']);
  const verification=page.locator('#code + #verification');
  await expect(verification).toContainText('100,000 steps checked in every dimension.');
  await expect(verification).toContainText('100,001 vertices and 5,000,050,000 vertex pairs');
  await expect(verification.locator('.verification-reports a')).toHaveCount(4);
  for(const d of ['3','4','5','6'])await expect(verification.getByRole('link',{name:new RegExp(`^${d}D report`)})).toHaveAttribute('href',`https://github.com/q5m-ai/basis-walk/blob/main/results/${d}d-100000.json`);
  await expect(page.locator('.hero-copy > .eyebrow')).toHaveText('Beyond Brown–Gerver–Ramsey');
  await expect(page.locator('.hero .lede')).toContainText('three, four and six dimensions');
  await expect(page.locator('.hero').getByRole('link',{name:'Read the paper on arXiv ↗',exact:true})).toHaveAttribute('href','https://arxiv.org/abs/2609.20366');
  await expect(page.locator('.hero-credits')).toHaveCount(0);
  await expect(page.locator('.hero img, .hero svg')).toHaveCount(0);
  const copy=await page.locator('.hero-copy').boundingBox(),explorer=await page.locator('.explorer').boundingBox();
  expect(Math.abs(copy.width-explorer.width)).toBeLessThan(1);
  expect(await page.evaluate(()=>document.querySelector('#walk').getBoundingClientRect().bottom<innerHeight)).toBe(true);
  await page.screenshot({path:'.local/above-fold.png'});
  await page.locator('#view-options summary').click();
  await expect(page.locator('.hero a[href="https://erdos-193.q5m.ai/"]')).toBeVisible();
  await expect(page.locator('#check')).toHaveCount(0);
  for(const d of ['3','4','5','6']){
    await page.selectOption('#dimension',d);
    await expect(page.locator('#map-columns tr')).toHaveCount(Number(d));
    await expect(page.locator('#projection')).toContainText('2D screen');
    if(d==='6')await expect(page.locator('#projection')).toContainText('six evenly spaced horizontal spokes');
    const coordinates=await page.locator('#coordinates').textContent();
    await page.locator('#compression').fill('24');
    await expect(page.locator('#view-label')).toContainText('1/24');
    await expect(page.locator('#coordinates')).toHaveText(coordinates);
    await page.click('#uncompressed');
    await expect(page.locator('#view-label')).toContainText('uncompressed');
    await expect(page.locator('#coordinates')).toHaveText(coordinates);
  }
  await page.click('#reset');
  await expect(page.locator('#compression')).toHaveValue('64');
  await page.locator('#projection-details summary').click();
  await expect(page.locator('#map-caption')).toContainText('illustrative');
  await expect(page.locator('#map-columns tr').first().locator('td')).toHaveText(['1','0','1']);
  await page.locator('#projection-details summary').click();
  await page.locator('#reveal').fill('32');
  await expect(page.locator('#coordinates')).toContainText('P32');
  await page.locator('#walk').focus();await page.keyboard.press('ArrowRight');
  await page.screenshot({path:'.local/desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'.local/mobile.png',fullPage:true});
  expect(errors).toEqual([]);expect(external).toEqual([]);
});
test('dragging and keyboard rotation keep the same scale and pivot',async({page})=>{
  await page.goto(base);
  for(const dimension of ['3','4','5','6']){
    await page.selectOption('#dimension',dimension);
    const canvas=page.locator('#walk');
    const scale=await canvas.getAttribute('data-view-scale');
    const center=await canvas.getAttribute('data-view-center');
    const coordinates=await page.locator('#coordinates').textContent();
    const before=await canvas.screenshot();
    const rect=await canvas.boundingBox();
    await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);
    await page.mouse.down();await page.mouse.move(rect.x+rect.width/2+80,rect.y+rect.height/2+45,{steps:8});await page.mouse.up();
    await canvas.focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowUp');
    await expect(canvas).toHaveAttribute('data-view-scale',scale);
    await expect(canvas).toHaveAttribute('data-view-center',center);
    await expect(page.locator('#coordinates')).toHaveText(coordinates);
    expect((await canvas.screenshot()).equals(before)).toBe(false);
  }
});
test('long-prefix rendering, zoom and colors leave integer coordinates unchanged',async({page})=>{
  await page.goto(base);
  await page.locator('#steps').fill('8192');
  await expect(page.locator('#coordinates')).toContainText('P8192');
  await expect(page.locator('#step-count')).toHaveText('8,192');
  const coordinates=await page.locator('#coordinates').textContent();
  const before=await page.locator('#walk').screenshot();
  await page.locator('#walk').hover();await page.mouse.wheel(0,-300);
  await expect.poll(async()=>!(await page.locator('#walk').screenshot()).equals(before)).toBe(true);
  await expect(page.locator('#coordinates')).toHaveText(coordinates);
  await page.locator('#view-options summary').click();
  await page.selectOption('#color-mode','direction');
  await expect(page.locator('#legend span')).toHaveCount(3);
  await expect(page.locator('#coordinates')).toHaveText(coordinates);
  await page.click('#play');
  await expect(page.locator('#play')).toHaveText('Pause');
  await expect.poll(async()=>Number(await page.locator('#reveal').inputValue())).toBeGreaterThan(0);
  await page.click('#play');
  await expect(page.locator('#play')).toHaveText('Play');
});
test('formula summary and 3D basis diagram are labeled and fit a small screen',async({page})=>{
  await page.goto(base);
  await page.locator('.hero a[href="#basis-rule"]').click();
  await expect(page.locator('#basis-rule math')).toHaveCount(2);
  await expect(page.locator('#basis-rule math').first()).toBeVisible();
  await expect(page.getByRole('img',{name:'The three positive standard basis vectors in 3D'})).toBeVisible();
  await expect(page.locator('.basis-diagram svg')).toContainText('(1, 0, 0)');
  await expect(page.locator('.basis-diagram svg')).toContainText('(0, 1, 0)');
  await expect(page.locator('.basis-diagram svg')).toContainText('(0, 0, 1)');
  await expect(page.locator('.basis-diagram figcaption')).toContainText('Illustrative 2D');
  const bounds=page.locator('#proof details');
  await expect(bounds).toContainText('six vertices of this 3D construction');
  await expect(bounds).toContainText('five-direction 5D candidate checked for 600,000 terms, but not proved');
  await page.setViewportSize({width:320,height:740});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.locator('#basis-rule').screenshot({path:'.local/basis-rule-mobile.png'});
});
test('styled workbench connects edited code to output on desktop and mobile',async({page})=>{
  await page.goto(base);
  await expect(page.locator('.tok-keyword').first()).toHaveText('def');
  await expect(page.locator('.source-panel .panel-head #example')).toHaveValue('return');
  await expect(page.locator('#code')).not.toContainText('All checkers');
  await expect(page.locator('#code')).not.toContainText('No imports');
  await expect(page.locator('#code')).not.toContainText('Ctrl/⌘');
  await expect(page.locator('#sources')).toContainText('arXiv:2609.20366');
  await expect(page.locator('#sources').getByRole('link',{name:'Paper on arXiv ↗',exact:true})).toHaveAttribute('href','https://arxiv.org/abs/2609.20366');
  await expect(page.locator('#sources').getByRole('link',{name:'Submitted version · PDF',exact:true})).toHaveAttribute('href','brown-gerver-ramsey-theorems.pdf');
  const source=await page.locator('.source-panel').boundingBox();
  const output=await page.locator('.output-panel').boundingBox();
  expect(output.x).toBeGreaterThan(source.x);
  await page.locator('#python-code').fill('print("<img src=x onerror=alert(1)>")\n# local text only');
  await expect(page.locator('#code-highlight code')).toHaveText('print("<img src=x onerror=alert(1)>")\n# local text only\n');
  await expect(page.locator('#code-highlight img')).toHaveCount(0);
  await expect(page.locator('#run-status')).toContainText('Edited');
  await page.locator('#fullscreen-code').click();
  await expect(page.locator('#fullscreen-code')).toHaveAttribute('aria-pressed','true');
  await page.keyboard.press('Escape');
  await expect(page.locator('#fullscreen-code')).toHaveAttribute('aria-pressed','false');
  await page.locator('#reset-code').click();
  await expect(page.locator('#python-code')).toHaveValue(/def basis_walk\(n, d=4\):/);
  expect((await page.locator('#python-code').inputValue()).split('\n').length).toBeLessThanOrEqual(18);
  await page.selectOption('#example','six');
  await expect(page.locator('#python-code')).toHaveValue(/def basis_walk\(n\):/);
  await page.selectOption('#example','return');
  await expect(page.locator('#python-code')).toHaveValue(/def basis_walk\(n, d=4\):/);
  await page.locator('#python-code').fill('print("saved draft")');
  await page.selectOption('#example','six');
  await page.selectOption('#example','return');
  await expect(page.locator('#python-code')).toHaveValue('print("saved draft")');
  await page.locator('#reset-code').click();
  await expect(page.locator('#python-code')).toHaveValue(/def basis_walk\(n, d=4\):/);
  const stepWords=page.locator('.step-words');
  await expect(stepWords).toContainText('How the symbols become steps.');
  await expect(stepWords).toContainText('Only the final digit strings are step words');
  await expect(stepWords).toContainText('These letters organize the construction; they are not directions yet.');
  await expect(stepWords).toContainText('There is no A–E source word. Each adjacent state pair');
  await expect(stepWords.locator('code')).toHaveCount(4);
  await expect(stepWords.locator('#step-word-6')).toHaveText('04301504342304301501251504301504');
  await page.setViewportSize({width:390,height:844});
  // Read both rects in one frame: viewport resize can change scroll anchoring.
  await expect.poll(()=>page.evaluate(()=>{
    const source=document.querySelector('.source-panel').getBoundingClientRect();
    const output=document.querySelector('.output-panel').getBoundingClientRect();
    return output.top>=source.bottom;
  })).toBe(true);
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('footer uses aligned local brand icons and wraps without overflow',async({page})=>{
  await page.goto(base);
  const footer=page.locator('.sitefoot');
  await expect(footer).toContainText('Made in Canada by ekalvi & Shallit and Belgium by Stijn');
  await expect(footer.getByRole('link',{name:'Shallit',exact:true})).toHaveAttribute('href','https://cs.uwaterloo.ca/~shallit/');
  await expect(footer.locator('.country-flag')).toHaveCount(2);
  await expect(footer.getByRole('link',{name:/KU Leuven Campus Kulak-Kortrijk/})).toHaveAttribute('href','https://wms.cs.kuleuven.be/cs/english');
  await expect(footer.getByRole('link',{name:/University of Waterloo/})).toHaveAttribute('href','https://cs.uwaterloo.ca/');
  await expect(footer.locator('.institution-logo')).toHaveCount(2);
  for(const logo of await footer.locator('.institution-logo').all())await expect(logo).toHaveCSS('filter','none');
  await expect.poll(()=>footer.locator('.institution-logo').evaluateAll(images=>images.every(img=>img.complete&&img.naturalWidth>0))).toBe(true);
  await expect(footer).not.toContainText('Mathematics');
  await expect(footer).not.toContainText('Software');
  await expect(page.locator('#sources')).toContainText('Stijn Cambie, Erik Kalviainen & Jeffrey Shallit');
  await expect(footer.getByRole('link',{name:'q5m',exact:true})).toHaveAttribute('href','https://www.q5m.ai');
  await expect(footer.getByRole('link',{name:'GitHub',exact:true})).toHaveAttribute('href','https://github.com/q5m-ai/basis-walk');
  await expect(footer.locator('.footer-icon[aria-hidden="true"]')).toHaveCount(2);
  await expect(footer).toHaveCSS('text-transform','uppercase');
  await expect(footer).toHaveCSS('border-top-width','1px');
  await footer.screenshot({path:'.local/footer-desktop.png'});
  await page.setViewportSize({width:320,height:740});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await footer.screenshot({path:'.local/footer-mobile.png'});
});
test('Python worker can stop and reports blocked runtime',async({page})=>{
  await page.route('https://cdn.jsdelivr.net/**',route=>route.abort());
  await page.goto(base);await page.click('#run-python');
  await expect(page.locator('#python-output')).toContainText('Error');
  await expect(page.locator('#run-status')).toHaveText('Failed');
  await expect(page.locator('#run-python')).toBeEnabled();
  await page.unroute('https://cdn.jsdelivr.net/**');
  await page.click('#run-python');await page.click('#stop-python');
  await expect(page.locator('#python-output')).toContainText('Stopped.');
  await expect(page.locator('#run-python')).toBeEnabled();
});
test('live pinned Pyodide executes exact checker',async({page})=>{
  test.skip(!process.env.TEST_PYODIDE,'Opt in to external CDN integration with TEST_PYODIDE=1');
  const pythonDownloads=[];
  page.on('request',request=>{if(new URL(request.url()).pathname.endsWith('/walks.py'))pythonDownloads.push(request.url());});
  await page.route('**/walks.py',route=>route.abort());
  await page.goto(base);await page.click('#run-python');
  await expect(page.locator('#python-output')).toContainText('[0, 0, 0, 0]',{timeout:120000});
  await expect(page.locator('#run-status')).toHaveText('Finished');
  await expect(page.locator('#python-output')).not.toContainText('finite-prefix-pass');
  await page.selectOption('#example','check');
  await expect(page.locator('#python-code')).toHaveValue(/def basis_walk\(n\):[\s\S]*def check\(n=128\):/);
  await page.click('#run-python');
  await expect(page.locator('#python-output')).toContainText('finite-prefix-pass',{timeout:120000});
  expect(pythonDownloads).toEqual([]);
  await expect(page.locator('#run-python')).toBeEnabled();
  await expect(page.locator('#run-status')).toHaveText('Finished');
  await page.locator('#python-code').fill('print("edited output")');
  await page.locator('#python-code').press('Control+Enter');
  await expect(page.locator('#python-output')).toContainText('edited output',{timeout:120000});
  await expect(page.locator('#python-output')).not.toContainText('finite-prefix-pass');
  await expect(page.locator('#run-python')).toBeEnabled();
});
